name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily
  workflow_dispatch:     # Allows manual runs
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v2
        with:
          github_user_name: ANUJ-D09
          svg_out_path: ./assets/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: ./assets/github-contribution-grid-snake.svg
